name: cao_project_nustudents
description: A new version of NU-Students developed by different developers for a University project at NIIT University

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  material_design_icons_flutter: ^4.0.5345
  liquid_swipe: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat.ttf